version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck       # Check for unchecked errors
    - govet          # Vet examines Go source code
    - ineffassign    # Detect ineffectual assignments
    - staticcheck    # Static analysis (includes gosimple and unused)
    - misspell       # Check for misspelled words
    - revive         # Golint replacement
    - gosec          # Security checks
    - gocritic       # Comprehensive checks
    - prealloc       # Slice preallocation

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    excludes:
      - G204  # Subprocess with variable (needed for helm/kubectl)
      - G304  # File path from variable (needed for helmfile)

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam

    # Allow print functions in main
    - path: cmd/
      linters:
        - forbidigo

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    stdout: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
