repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: nginx
    namespace: default
    chart: bitnami/nginx
    version: 15.0.0
    wait: true
    values:
      - values-nginx.yaml
    set:
      - name: service.type
        value: ClusterIP

  - name: redis
    namespace: default
    chart: bitnami/redis
    version: 18.0.0
    wait: false
    values:
      - values-redis.yaml
